<a href="https://colab.research.google.com/github/Rumaizakosar/Eight-Puzzle-Code/blob/main/DM_Distance_Formula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances


In [10]:
from google.colab import files
uploaded = files.upload()

titanic_data = pd.read_csv('/content/Titanic-Dataset.csv')
titanic_data.head()


Saving Titanic-Dataset.csv to Titanic-Dataset (1).csv


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
titanic_data = titanic_data.dropna()  # Example of dropping missing values
titanic_data['Sex'] = titanic_data['Sex'].map({'male': 1, 'female': 0})  # Encode categorical variable


<ipython-input-4-f6c722c7e176>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic_data['Sex'] = titanic_data['Sex'].map({'male': 1, 'female': 0})  # Encode categorical variable


In [8]:
numerical_data = titanic_data[['Age', 'Fare']]  # Select numerical columns
euclidean_distances = pairwise_distances(numerical_data, metric='euclidean')
manhattan_distances = pairwise_distances(numerical_data, metric='manhattan')

print("Euclidean Distances:\n", euclidean_distances)
print("Manhattan Distances:\n", manhattan_distances)


Euclidean Distances:
 [[ 0.         18.42911823 25.16281925 ... 21.56422095 45.44569131
  42.99198598]
 [18.42911823  0.         19.04025752 ... 36.66744331 28.1
  24.79132913]
 [25.16281925 19.04025752  0.         ... 31.35964122 41.26704383
  35.5242017 ]
 ...
 [21.56422095 36.66744331 31.35964122 ...  0.         64.7673132
  61.03937138]
 [45.44569131 28.1        41.26704383 ... 64.7673132   0.
   7.        ]
 [42.99198598 24.79132913 35.5242017  ... 61.03937138  7.
   0.        ]]
Manhattan Distances:
 [[ 0.     21.1833 35.4208 ... 29.875  60.2833 53.2833]
 [21.1833  0.     20.2375 ... 51.0583 39.1    32.1   ]
 [35.4208 20.2375  0.     ... 33.2958 56.8625 49.8625]
 ...
 [29.875  51.0583 33.2958 ...  0.     90.1583 83.1583]
 [60.2833 39.1    56.8625 ... 90.1583  0.      7.    ]
 [53.2833 32.1    49.8625 ... 83.1583  7.      0.    ]]


In [7]:
categorical_data = titanic_data[['Pclass', 'Sex', 'Embarked']]  # Select categorical columns
categorical_data = pd.get_dummies(categorical_data)  # Convert categorical to numerical

hamming_distances = pairwise_distances(categorical_data, metric='hamming')

print("Hamming Distances:\n", hamming_distances)



Hamming Distances:
 [[0.  0.4 0.6 ... 0.  0.4 0.2]
 [0.4 0.  0.2 ... 0.4 0.  0.6]
 [0.6 0.2 0.  ... 0.6 0.2 0.4]
 ...
 [0.  0.4 0.6 ... 0.  0.4 0.2]
 [0.4 0.  0.2 ... 0.4 0.  0.6]
 [0.2 0.6 0.4 ... 0.2 0.6 0. ]]
